#docker-compose.yml
version: "3.8"
services:
    #PHP
    web-php:
        container_name: c-web-php
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            - D:/5-research/1-gh/1-tailieuweb/laravel-8x:/home/sites
        working_dir: /home/sites
    #Composer
    web-composer:
        container_name: c-web-composer
        image: composer/composer
        volumes:
            - D:/5-research/1-gh/1-tailieuweb/laravel-8x:/home/sites
        working_dir: /home/sites
        command: install
    #Apache
    web-apache:
        container_name: c-web-apache
        build: ./apache
        links:
            - web-php
        ports:
            - "8000:80"
        volumes:
            - D:/5-research/1-gh/1-tailieuweb/laravel-8x:/home/sites
            - ./apache/logs:/var/log/apache2
    #MySQL
    web-mysql:
        container_name: c-web-mysql
        image: "mysql:5.6.40"
        hostname: h-web-mysql
        restart: always
        ports:
            - "3309:3306"
        volumes:
            - ./mysql/db:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
    #phpMyAdmin
    phpmyadmin:
        image: phpmyadmin
        restart: always    
        ports:
            - "7070:80"
        environment:
            - PMA_ARBITRARY=1