#network
networks:
    web-network:
        driver: bridge

services:
    #PHP
    web-php:
        container_name: c-php-web
        build:
            dockerfile: Dockerfile
            context: ./php/
        hostname: h-php-web
        restart: always
        networks:
            - web-network
        ports:
            - "8080:80"
        volumes:
            - ./prj/moodle:/var/www/html
    #MySQL
    web-mysql:
        container_name: c-mysql-web
        build:
            context: ./mysql
        restart: always
        networks:
            web-network:
                aliases:
                    - web-mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/db:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf        
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #phpMyAdmin
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        networks:
            - web-network
        depends_on:
            - web-mysql
        environment:
            - PMA_HOST=web-mysql
            - PMA_PORT=3306