version: "3"

#network
networks:
    web-network:
        driver: bridge

services:
    #PHP
    web-php:
        container_name: c-php-web
        build:
            dockerfile: Dockerfile
            context: ./php/
        hostname: h-php-web
        restart: always
        networks:
            - web-network
        volumes:
            - D:/6-docker/docker_dev/public_html/src1/:/home/sites
    #HTTPD
    web-httpd:
        container_name: c-httpd-web
        image: "httpd:2.4.43"
        hostname: h-httpd-web
        restart: always
        networks:
            - web-network
        volumes:
            - D:/6-docker/docker_dev/public_html/src1/:/home/sites/
            - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
            - "70:80"
    #MySQL
    web-mysql:
        container_name: c-mysql-web
        image: "mysql:5.6.40"
        hostname: h-mysql-web
        restart: always
        networks:
            - web-network
        ports:
            - "3309:3306"
        volumes:
            - ./mysql/db:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
    #phpMyAdmin
    phpmyadmin:
        image: phpmyadmin
        restart: always    
        ports:
            - "7070:80"
        networks:
            - web-network
        environment:
            - PMA_ARBITRARY=1